services:
  api:
    extends:
      file: docker-compose.yml
      service: api

  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    volumes:
      - ./nginx/vps.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
      - ./nginx/certbot/conf:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    ports: !reset []
